//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quartz.WindowsService {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class QuartzResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QuartzResources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Quartz.WindowsService.QuartzResources", typeof(QuartzResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore recupero configurazioni da database.
        /// </summary>
        internal static string DbError {
            get {
                return ResourceManager.GetString("DbError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore non gestito.
        /// </summary>
        internal static string GenericError {
            get {
                return ResourceManager.GetString("GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Avvio in modalità Windows Service (Headless).
        /// </summary>
        internal static string HeadlessInfo {
            get {
                return ResourceManager.GetString("HeadlessInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Creazione Job e Trigger con configurazione: {0}.
        /// </summary>
        internal static string NewSchedulerInfo {
            get {
                return ResourceManager.GetString("NewSchedulerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a OnContinue error.
        /// </summary>
        internal static string OnContinueError {
            get {
                return ResourceManager.GetString("OnContinueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Esecuzione OnContinue.
        /// </summary>
        internal static string OnContinueInfo {
            get {
                return ResourceManager.GetString("OnContinueInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Esecuzione OnDebug.
        /// </summary>
        internal static string OnDebugInfo {
            get {
                return ResourceManager.GetString("OnDebugInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore Batch Service in modalità interattiva (OnDebug).
        /// </summary>
        internal static string OnMainDebugError {
            get {
                return ResourceManager.GetString("OnMainDebugError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a OnPause error.
        /// </summary>
        internal static string OnPauseError {
            get {
                return ResourceManager.GetString("OnPauseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Esecuzione OnPause.
        /// </summary>
        internal static string OnPauseInfo {
            get {
                return ResourceManager.GetString("OnPauseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a OnStart error.
        /// </summary>
        internal static string OnStartError {
            get {
                return ResourceManager.GetString("OnStartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Esecuzione OnStart.
        /// </summary>
        internal static string OnStartInfo {
            get {
                return ResourceManager.GetString("OnStartInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a OnStop error.
        /// </summary>
        internal static string OnStopError {
            get {
                return ResourceManager.GetString("OnStopError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Esecuzione OnStop.
        /// </summary>
        internal static string OnStopInfo {
            get {
                return ResourceManager.GetString("OnStopInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Provo ad eseguire il kill dei processi: {0}.
        /// </summary>
        internal static string OnStopProcessesKill {
            get {
                return ResourceManager.GetString("OnStopProcessesKill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Piani di esecuzione in cache scaduti.
        /// </summary>
        internal static string PlainExpiredInfo {
            get {
                return ResourceManager.GetString("PlainExpiredInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Non ho trovato piani di esecuzione a database per il batch {0} e server {1}. Non attivo lo scheduler quartz e la cache dei piani di esecuzione.
        /// </summary>
        internal static string PlainLoadNotFoundError {
            get {
                return ResourceManager.GetString("PlainLoadNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Piani di esecuzion in cache scaduti error. Si mantengono quelli attuali.
        /// </summary>
        internal static string PlainReloadError {
            get {
                return ResourceManager.GetString("PlainReloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ricaricarti nuovi piani di esecuzione in cache.
        /// </summary>
        internal static string PlainReloadInfo {
            get {
                return ResourceManager.GetString("PlainReloadInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Non ho trovato piani di esecuzione a database per il batch {0} e server {1}. Si mantengono quelli attuali.
        /// </summary>
        internal static string PlainReloadNotFoundError {
            get {
                return ResourceManager.GetString("PlainReloadNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Current Working Directory dopo set forzato: {0}.
        /// </summary>
        internal static string PostCurrentDirectoryInfo {
            get {
                return ResourceManager.GetString("PostCurrentDirectoryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Current Working Directory prima di set forzato: {0}.
        /// </summary>
        internal static string PreCurrentDirectoryInfo {
            get {
                return ResourceManager.GetString("PreCurrentDirectoryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Richedulati Job quartz con nuovi piani di esecuzione Cron.
        /// </summary>
        internal static string RescheduleJobInfo {
            get {
                return ResourceManager.GetString("RescheduleJobInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Avvio in modalità UserInteractive.
        /// </summary>
        internal static string UserInteractiveInfo {
            get {
                return ResourceManager.GetString("UserInteractiveInfo", resourceCulture);
            }
        }
    }
}
